# version: '3'
name: lobby
services:
  web_server:
    image: nginx:1.21.4-alpine
    volumes:
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./apps/nginx/default.conf.dev:/etc/nginx/conf.d/default.conf
      - ./apps/nginx:/var/www/
    ports:
      - "80:80"
    networks:
      - docker

  db:
    image: postgres:16-alpine3.19
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lobby
    ports:
      - "5432:5432"
    networks:
      - docker

  # db_test:
  #   image: postgres:16-alpine3.19
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: lobby_test
  #   ports:
  #     - "5433:5432"
  #   networks:
  #     - docker

networks:
  docker:
    driver: bridge
volumes:
  db-data:
