# version: '3'
name: lobby
services:
  db:
    image: postgres:16-alpine3.19
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lobby
    ports:
      - "5432:5432"
    networks:
      - docker

  db_test:
    image: postgres:16-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lobby_test
    ports:
      - "5433:5432"
    networks:
      - docker

  backend:
    image: node:20.12.2-alpine3.19
    restart: unless-stopped
    working_dir: /apps/backend
    volumes:
      - ./backend:/apps/backend
      - ../packages/domain:/packages/domain
      - ../packages/socket:/packages/socket
    ports:
      - "3001:3001"
    entrypoint: /bin/sh -c "sh entrypoint.sh; sleep infinity"
    depends_on:
      - db
    networks:
      - docker
  heartbeat:
    image: node:20.12.2-alpine3.19
    restart: unless-stopped
    working_dir: /apps/heartbeat
    volumes:
      - ./heartbeat:/apps/heartbeat
      - ../packages/domain:/packages/domain
    ports:
      - "2999:2999"
    entrypoint: /bin/sh -c "sh entrypoint.sh; sleep infinity"
    depends_on:
      - db
      - backend
    networks:
      - docker
  frontend:
    image: node:20.12.2-alpine3.19
    restart: unless-stopped
    working_dir: /apps/frontend
    environment:
      - NUXT_PUBLIC_BACKEND_URL=http://127.0.0.1:3001
    volumes:
      - ./frontend:/apps/frontend
      - ../packages/domain:/packages/domain
      - ../packages/socket:/packages/socket
    ports:
      - "3000:3000"
    entrypoint: /bin/sh -c "sh entrypoint.sh; sleep infinity"
    depends_on:
      - db
    networks:
      - docker
networks: 
  docker: 
    driver: bridge
volumes:
  db-data: