# version: '3'
name: lobby
services:
  db:
    image: postgres:16-alpine3.19
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lobby
    ports:
      - "5432:5432"
    networks:
      - docker
  db_test:
    image: postgres:16-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lobby_test
    ports:
      - "5433:5432"
    networks:
      - docker

  backend:
    image: node:20.12.2-alpine3.19
    working_dir: /apps/backend
    volumes:
      - ./backend:/apps/backend
      - ../packages/domain:/packages/domain
      - ../packages/socket:/packages/socket
    ports:
      - "3001:3001"
    command: sh -c "
        npm install &&
        npm run build &&
        npm start"
    depends_on:
      - db
    networks:
      - docker
  heartbeat:
    image: node:20.12.2-alpine3.19
    working_dir: /apps/heartbeat
    volumes:
      - ./heartbeat:/apps/heartbeat
      - ../packages/domain:/packages/domain
    ports:
      - "2999:2999"
    command: sh -c "
        npm install &&
        npm run build &&
        npm start"
    depends_on:
      - db
      - backend
    networks:
      - docker

networks: 
  docker: 
    driver: bridge
volumes:
  db-data: