name: Build the Web Frontend Service

on:
  push:
    branches:
      - main
    paths: 
    - 'apps/frontend/**'
    - 'packages/**'
    - '.github/workflows/**'

  pull_request:
    branches:
      - main
      - dev
    paths: 
      - 'apps/frontend/**'
      - 'packages/**'
      - '.github/workflows/**'

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.0
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install Package & Setup
        run: pnpm install --frozen-lockfile --filter=frontend... -w
      - name: Try to build
        run: pnpm dlx turbo build --filter=frontend...
